CREATE TABLE EMONEY(
    EMONEY_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_SEQ BIGINT,
    ORDER_SEQ BIGINT,
    TYPE_SEQ BIGINT,
    AMOUNT BIGINT,
    USED_AMONUT BIGINT,
    REMAIN_AMOUNT BIGINT,
    EXPIRATION_DATE TIMESTAMP,
    IS_APPROVED BOOLEAN DEFAULT FALSE,
    CONTENT VARCHAR(100)
)

CREATE TABLE EMONEY_USAGE_HISTORY(
    EMONEY_USAGE_HISTORY_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    USAGE_AMOUNT BIGINT,
    CONTENT VARCHAR(100),
    EMONEY_SEQ BIGINT,
    FOREIGN KEY (EMONEY_SEQ) REFERENCES EMONEY(EMONEY_SEQ)
)